# Generated by Django 2.1.5 on 2019-07-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='issues.Location', to_field='lid'),
        ),
    ]
