# Generated by Django 2.1.3 on 2018-12-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='body',
            new_name='text',
        ),
    ]
