# Generated by Django 2.1.7 on 2019-07-23 19:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20190702_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
