# Generated by Django 2.1.3 on 2019-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20181217_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
