# Generated by Django 2.1.5 on 2019-02-07 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20190103_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
