# Generated by Django 2.1.5 on 2019-09-04 16:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('issues', '0003_issue_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
