# Generated by Django 2.1.5 on 2019-02-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20190207_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
