# Generated by Django 2.1.8 on 2019-04-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20190211_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'sensors_location',
                'ordering': ['lid'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Location', to_field='lid'),
        ),
    ]
